### PR TITLE
small bug fix with unpermitted params

### PR DESCRIPTION
**Pull request by alexistorosina1**
in the method workout_params included params.require(:workout) to ensure the hash contains a workout key

### CODE REVIEW

**Comment by chris-t-li** [comment]
Why are we deleting lines 15 - 19 and 40 - 42 in workouts_controller? Is this logic being rendered elsewhere or replaced, otherwise how are we fetching the leaderboard?

Screen Shot 2023-04-10 at 1 20 34 PM

**Review by chris-t-li — CHANGES_REQUESTED** [review]
See above comment and screenshot

**Comment by alexistorosina1** [comment]
youre, right, lines 15-19 & update_leaderboard method shouldnt be removed

**Comment by chris-t-li** [comment]
Can you fix, and then push again?

**Review by chris-t-li — APPROVED** [review]
Approved. Thanks!

**Pull request merged**
