### PR TITLE
add additional fields to sign up form

### PR DESCRIPTION
**Pull request by chris-t-li**
1. Add additional permitted parameters to authentication controller for sign up
2. Move location of sign up form toggle between sign up and login
3. Add additional input tags to sign up form

### CODE REVIEW

**Comment by chris-t-li** [comment]
1. Add "auth/update_profile" route and options for pre-flight
2. Add update method to Users controller
3. Removed validate presence of password in User model (this was creating an error when trying to update User params)
4. Created an Edit Profile Modal - will open when user clicks "Edit Profile"
5. Add useUpdateProfileMutation for user patch request

Note: current patch method does not dynamically render updated user details on client, however database will have been updated. If user logs out and logs back in, updated details will persist. Next PR will address.

**Comment by chris-t-li** [comment]
Fixed the issue from above comment. When user updates their profile, response object is used to update state and local storage so that edits to user profile will persist. 

setUserInfo reducer has been updated in userslice so that it will only set the user parameters if it is is included in action.payload (i.e. if workouts/competitions are not in action.payload, setUserInfo function will not set those values to undefined). Achieved using the below forEach loop.

```
Object.keys(action.payload).forEach(key => {
        state[key] = action.payload[key];
      });
```

instead of the below, which would set workouts to undefined if workouts was not included in the payload
```
      const { user, token, workouts, competitions } = action.payload;
      state.user = user;
      state.token = token;
      state.workouts = workouts;
      state.competitions = competitions;
```

**Review by dkussainov — APPROVED** [review]
reviewed

**Comment by dkussainov** [comment]
Great idea with forEach ! Solves the issue!

**Pull request merged**
